apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  server_password: {{ required "A valid .Values.mumble.server_password entry required!" .Values.mumble.server_password | b64enc }}
  superuser_password: {{ required "A valid .Values.mumble.superuser_password entry required!" .Values.mumble.superuser_password | b64enc }}
