apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumbleserver.fullname" . }}
  labels:
    {{- include "mumbleserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 64738
      targetPort: mumble-tcp
      protocol: TCP
      name: mumble-tcp
    - port: 64738
      targetPort: mumble-udp
      protocol: UDP
      name: mumble-udp
  selector:
    {{- include "mumbleserver.selectorLabels" . | nindent 4 }}
